import { decodeBase64 } from './base64';
import type { GeometrySource } from './geometry-source';
import { EMPTY_GEOMETRY } from './geometry-source';
import { decodeMvtTile } from './mvt-mapping';
import { packGeometry, type PackedGeometry } from './packed-geometry';
import type { TileCoord } from './tile-math';
import { tileKeyOf } from './tile-math';

import { FIXTURE_TILES } from './__fixtures__/caphill-tiles';

/**
 * Serves the bundled Capitol Hill sample tiles (generated by
 * scripts/make-tile-fixtures.ts) through the exact same MVT decode path as the
 * real tile server — the app's offline/dev data source until
 * EXPO_PUBLIC_TILE_URL points at a live tile server.
 */
export class FixtureGeometrySource implements GeometrySource {
  constructor(private readonly tiles: Record<string, string> = FIXTURE_TILES) {}

  getTile(tile: TileCoord): Promise<PackedGeometry> {
    const b64 = this.tiles[tileKeyOf(tile.z, tile.x, tile.y)];
    if (!b64) return Promise.resolve(EMPTY_GEOMETRY);
    return Promise.resolve(packGeometry(decodeMvtTile(decodeBase64(b64), tile)));
  }
}
