import { readFileSync } from 'fs';
import { join } from 'path';

import { decodeMvtTile } from '../mvt-mapping';
import { packedTileToGeometry, unpackPacked } from '../packed-geometry';
import { wrapScg1 } from '../scg1';
import type { TileCoord } from '../tile-math';

/**
 * Parity: the JS SCG1 reader (`wrapScg1`) over a buffer emitted by the native
 * Rust encoder must reproduce the JS MVT decoder's geometry on a real tile.
 * The `.scg1` fixture is regenerated by the Rust `generate_scg1_fixture` test.
 */
const DIR = join(process.cwd(), 'modules/iroh-location/rust/tests/fixtures');
const TILE: TileCoord = { z: 10, x: 164, y: 357 };

const ringPts = (areas: readonly { readonly rings: readonly (readonly unknown[])[] }[]) =>
  areas.reduce((n, a) => n + a.rings.reduce((m, r) => m + r.length, 0), 0);
const linePts = (ls: readonly { readonly points: readonly unknown[] }[]) =>
  ls.reduce((n, l) => n + l.points.length, 0);

describe('wrapScg1 parity with the JS decoder', () => {
  const mvt = new Uint8Array(readFileSync(join(DIR, 'z10_164_357.mvt')));
  const scg1 = new Uint8Array(readFileSync(join(DIR, 'z10_164_357.scg1')));

  const js = decodeMvtTile(mvt, TILE);
  const native = unpackPacked(packedTileToGeometry(wrapScg1(scg1)));

  it('matches feature and point counts', () => {
    expect(native.streets).toHaveLength(js.streets.length);
    expect(linePts(native.streets)).toBe(linePts(js.streets));
    expect(native.rivers).toHaveLength(js.rivers.length);
    expect(linePts(native.rivers)).toBe(linePts(js.rivers));
    expect(native.water).toHaveLength(js.water.length);
    expect(ringPts(native.water)).toBe(ringPts(js.water));
    expect(native.parks).toHaveLength(js.parks.length);
    expect(ringPts(native.parks)).toBe(ringPts(js.parks));
    expect(native.places).toHaveLength(js.places.length);
  });

  it('matches the first street (class + coordinates to f32 precision)', () => {
    expect(native.streets[0].roadClass).toBe(js.streets[0].roadClass);
    const [nx, ny] = native.streets[0].points[0];
    const [jx, jy] = js.streets[0].points[0];
    expect(nx).toBeCloseTo(jx, 5);
    expect(ny).toBeCloseTo(jy, 5);
  });

  it('matches place attributes (name / kind / rank)', () => {
    expect(native.places[0].name).toBe(js.places[0].name);
    expect(native.places[0].kind).toBe(js.places[0].kind);
    expect(native.places[0].rank).toBe(js.places[0].rank);
    expect(native.places.map((p) => p.name).sort()).toEqual(js.places.map((p) => p.name).sort());
  });

  it('preserves street names', () => {
    const named = js.streets.findIndex((s) => s.name);
    if (named >= 0) expect(native.streets[named].name).toBe(js.streets[named].name);
  });
});
