const { withAppBuildGradle } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Signs BOTH debug and release local builds with the dedicated streetCryptid
 * keystore (from credentials.json) instead of the throwaway debug.keystore.
 *
 * Why: Android only preserves app data across an (re)install when the signing
 * certificate matches. By signing the dev-client (debug) build AND release
 * builds with the same key we hand to Play App Signing, the on-device signature
 * is identical everywhere — so switching between a locally-built app and the
 * Play Store build no longer wipes SQLite / SecureStore data.
 *
 * `android/` is git-ignored and regenerated by `expo prebuild`, so this plugin
 * re-applies the change every prebuild. It reads the same credentials.json that
 * EAS uses, keeping one source of truth. If credentials.json is absent (e.g. a
 * fresh clone without the keystore) it no-ops and the default debug keystore is
 * used, so the build still succeeds.
 *
 * THAT "one source of truth" ONLY HOLDS IF THE KEYSTORE EAS HOLDS IS THIS ONE.
 * `eas.json` sets `credentialsSource: "remote"`, so EAS signs with the keystore
 * stored server-side — which must therefore be the same keystore credentials.json
 * points at (upload it via `eas credentials -p android`). If EAS is left holding
 * its own auto-generated keystore, this plugin's guarantee silently inverts: local
 * and EAS builds get DIFFERENT certificates, an EAS-built install refuses
 * `adb install -r` of a local build (INSTALL_FAILED_UPDATE_INCOMPATIBLE), and
 * crossing between them wipes app data.
 *
 * Do NOT "fix" a mismatch by flipping this to `credentialsSource: "local"`. CI runs
 * `eas build --local` on GitHub-hosted runners whose only EAS secret is EXPO_TOKEN;
 * credentials.json and credentials/ are git-ignored, so "local" leaves the runner
 * with no keystore at all and every CI build fails. Keeping it "remote" is what
 * lets EAS hand the key to the runner. Verify with:
 *   keytool -list -v -keystore credentials/streetcryptid.keystore | grep SHA256
 * and compare against a built APK's `apksigner verify --print-certs`.
 *
 * The keystore here is the Play App Signing (on-device) key — Play was enrolled
 * with our own key, and the upload key is the same key, so signing local builds
 * with it makes them match the on-device signature and update in place over the
 * Play install without wiping data.
 */
function loadKeystore(projectRoot) {
  const p = path.join(projectRoot, 'credentials.json');
  if (!fs.existsSync(p)) return null;
  try {
    const ks = JSON.parse(fs.readFileSync(p, 'utf8'))?.android?.keystore;
    if (ks?.keystorePath && ks?.keystorePassword && ks?.keyAlias && ks?.keyPassword) {
      return ks;
    }
  } catch (e) {
    console.warn(`[withSharedSigning] failed to parse credentials.json: ${e.message}`);
  }
  return null;
}

module.exports = function withSharedSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    const ks = loadKeystore(cfg.modRequest.projectRoot);
    if (!ks) {
      console.warn(
        '[withSharedSigning] credentials.json keystore missing — keeping default debug keystore.'
      );
      return cfg;
    }

    const abs = path.resolve(cfg.modRequest.projectRoot, ks.keystorePath).replace(/\\/g, '/'); // Gradle wants forward slashes, even on Windows

    const original =
      /storeFile file\('debug\.keystore'\)\s*\n\s*storePassword 'android'\s*\n\s*keyAlias 'androiddebugkey'\s*\n\s*keyPassword 'android'/;

    if (!original.test(cfg.modResults.contents)) {
      throw new Error(
        '[withSharedSigning] could not find the default debug signingConfig in build.gradle — ' +
          'the Expo template changed; update this plugin.'
      );
    }

    const replacement =
      `storeFile file('${abs}')\n` +
      `            storePassword '${ks.keystorePassword}'\n` +
      `            keyAlias '${ks.keyAlias}'\n` +
      `            keyPassword '${ks.keyPassword}'`;

    cfg.modResults.contents = cfg.modResults.contents.replace(original, replacement);
    return cfg;
  });
};
