const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Keeps key material and location history out of Android backups (FORWARD-SECRECY.md §6, §7
 * step 0). Android Auto Backup (cloud) and API 31+ device-to-device transfer would otherwise
 * capture:
 *
 * - `shared_prefs/SecureStore.xml` — expo-secure-store's EncryptedSharedPreferences file
 *   (identity + receiving secrets, the sequential `seq` counter, and later the ratchet state
 *   key). Its Keystore master key never leaves the device, so a restored copy is undecryptable
 *   garbage at best — and once key state is sequential, a *same-device* restore (uninstall →
 *   reinstall → auto-restore) would rewind counters, which is key reuse.
 * - `databases/` — `streetcryptid.social.db` holds friends' fixes as plaintext; the exploration
 *   and telemetry DBs are location-derived too. All excluded wholesale.
 * - `files/streetcryptid/` — the Rust node's **ratchet session state** (FORWARD-SECRECY.md §4.2).
 *   This is the one that must not be missed. Session state is sequential: a restored copy rewinds
 *   `ns`, the next publish re-derives a message key already used, and that key seals a different
 *   content key under the same zero nonce — repeated (key, nonce) in ChaCha20-Poly1305, which
 *   leaks the XOR of both plaintexts. Auto Backup includes `files/` by default, so this exclusion
 *   is what makes it safe to keep unrecoverable state there at all.
 *
 * The iroh node's docs/blobs store needs no rule here: `IrohLocationModule.kt` roots it at
 * `cacheDir/streetcryptid`, and cache is never included in Auto Backup or device transfer. That
 * split is deliberate — the replica is re-fetchable and may be purged; session state is neither,
 * which is why it lives in `filesDir` and is excluded here instead.
 *
 * `android/` is git-ignored and regenerated by `expo prebuild`, so this plugin re-applies the
 * change every prebuild (same pattern as withSharedSigning).
 */

const RES_XML = {
  // API ≤ 30 cloud backup (android:fullBackupContent).
  sc_backup_rules: `<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
    <exclude domain="sharedpref" path="SecureStore.xml" />
    <exclude domain="database" path="." />
    <exclude domain="file" path="streetcryptid" />
</full-backup-content>
`,
  // API 31+ cloud backup AND device-to-device transfer (android:dataExtractionRules).
  sc_data_extraction_rules: `<?xml version="1.0" encoding="utf-8"?>
<data-extraction-rules>
    <cloud-backup>
        <exclude domain="sharedpref" path="SecureStore.xml" />
        <exclude domain="database" path="." />
        <exclude domain="file" path="streetcryptid" />
    </cloud-backup>
    <device-transfer>
        <exclude domain="sharedpref" path="SecureStore.xml" />
        <exclude domain="database" path="." />
        <exclude domain="file" path="streetcryptid" />
    </device-transfer>
</data-extraction-rules>
`,
};

module.exports = function withBackupExclusion(config) {
  config = withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (!app) {
      throw new Error('[withBackupExclusion] AndroidManifest has no <application> element');
    }
    app.$['android:fullBackupContent'] = '@xml/sc_backup_rules';
    app.$['android:dataExtractionRules'] = '@xml/sc_data_extraction_rules';
    return cfg;
  });

  config = withDangerousMod(config, [
    'android',
    (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml'
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      for (const [name, contents] of Object.entries(RES_XML)) {
        fs.writeFileSync(path.join(xmlDir, `${name}.xml`), contents);
      }
      return cfg;
    },
  ]);

  return config;
};
