import { createHexGrid, hexKeyOf, parseHexKey } from '../hex';

/**
 * Reference vectors generated by running the design mock's literal `hexKey`
 * source (docs/design/mock_real.html) in Node: [x, y, R, expectedKey].
 */
const MOCK_VECTORS: readonly [number, number, number, string][] = [
  [0, 0, 42, '0,0'],
  [100, 50, 42, '2,0'],
  [63, 36.4, 42, '1,0'],
  [-30, 80, 42, '0,1'],
  [210, 371, 42, '3,4'],
  [371.2, 205.9, 58, '4,0'],
  [59.9, -120.3, 64, '1,-2'],
  [1000, 1000, 42, '16,6'],
  // world-space magnitudes (normalized mercator, hex radius ~5e-6)
  [0.1596, 0.3565, 5e-6, '21280,30525'],
  [0.15960001, 0.35650002, 5e-6, '21280,30525'],
  [0.159607, 0.356497, 5e-6, '21281,30524'],
  [0.5, 0.5, 1e-5, '33333,12201'],
  [0.4999963, 0.5000041, 1e-5, '33333,12201'],
];

describe('hex keys', () => {
  it('round-trip through parseHexKey, including negatives', () => {
    expect(parseHexKey(hexKeyOf(3, -4))).toEqual([3, -4]);
    expect(parseHexKey(hexKeyOf(-21280, 30525))).toEqual([-21280, 30525]);
  });
});

describe('keyAt', () => {
  it.each(MOCK_VECTORS)('matches the mock hexKey at (%f, %f) R=%f', (x, y, R, expected) => {
    expect(createHexGrid(R).keyAt([x, y])).toBe(expected);
  });
});

describe('center / keyAt consistency', () => {
  const samples: [number, number, number][] = [
    [12.3, 99.4, 42],
    [-77, 13, 42],
    [0.1596, 0.3565, 5e-6],
    [0.87, 0.12, 1e-5],
  ];

  it.each(samples)('center(keyAt(p)) is within R of p (%f, %f)', (x, y, R) => {
    const grid = createHexGrid(R);
    const [cx, cy] = grid.center(grid.keyAt([x, y]));
    expect(Math.hypot(cx - x, cy - y)).toBeLessThanOrEqual(R * (1 + 1e-9));
  });

  it('keyAt(center(k)) is the identity', () => {
    const grid = createHexGrid(42);
    for (const key of ['0,0', '3,-2', '-5,9', '17,4']) {
      expect(grid.keyAt(grid.center(key))).toBe(key);
    }
  });
});

describe('neighbors', () => {
  it('returns 6 distinct cells whose centers are √3·R away', () => {
    const R = 42;
    const grid = createHexGrid(R);
    const around = grid.neighbors('3,-1');
    expect(new Set(around).size).toBe(6);
    const [cx, cy] = grid.center('3,-1');
    for (const n of around) {
      const [nx, ny] = grid.center(n);
      expect(Math.hypot(nx - cx, ny - cy)).toBeCloseTo(Math.sqrt(3) * R, 9);
    }
  });
});

describe('cellsIn', () => {
  it('covers every point of the rect (no gaps)', () => {
    const grid = createHexGrid(10);
    const rect = { minX: 0, minY: 0, maxX: 100, maxY: 80 };
    const cells = new Set(grid.cellsIn(rect));
    for (let x = 0; x <= 100; x += 7) {
      for (let y = 0; y <= 80; y += 7) {
        expect(cells.has(grid.keyAt([x, y]))).toBe(true);
      }
    }
  });

  it('does not enumerate cells far outside the rect', () => {
    const grid = createHexGrid(10);
    const rect = { minX: 0, minY: 0, maxX: 100, maxY: 80 };
    for (const key of grid.cellsIn(rect)) {
      const [cx, cy] = grid.center(key);
      expect(cx).toBeGreaterThanOrEqual(rect.minX - 3 * 10);
      expect(cx).toBeLessThanOrEqual(rect.maxX + 3 * 10);
      expect(cy).toBeGreaterThanOrEqual(rect.minY - 3 * 10);
      expect(cy).toBeLessThanOrEqual(rect.maxY + 3 * 10);
    }
  });
});
