/**
 * Generate bundled MVT fixture tiles from the design archive's baked OSM data
 * (docs/design/mapdata.js, Capitol Hill set), in the same OpenMapTiles layer
 * schema the real tile server emits (OpenMapTiles).
 *
 * The output feeds `FixtureGeometrySource` (offline/dev map) and the tile
 * decode tests, so the full MVT → geometry → masks → dots pipeline runs
 * identically with or without a tile server.
 *
 * Run with: bun scripts/make-tile-fixtures.ts
 */

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import geojsonvt from 'geojson-vt';
import vtpbf from 'vt-pbf';

import { latLonToWorld } from '../src/features/map/core/mercator';
import { tilesCovering, tileKeyOf } from '../src/features/map/tiles/tile-math';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// ---- load the baked design-archive data (window-global script) -------------

interface MockWay {
  k: 's' | 'p' | 'w' | 'r' | 'c';
  c?: 0 | 1 | 2 | 3 | 4;
  nm?: string;
  g: [number, number][]; // [lat, lon]
}
interface MockSet {
  bbox: [number, number, number, number]; // [S, W, N, E]
  ways: MockWay[];
}

const mapdataSource = readFileSync(join(root, 'docs/design/mapdata.js'), 'utf8');
const windowShim: { OSMSETS?: Record<string, MockSet> } = {};
new Function('window', mapdataSource)(windowShim);
const caphill = windowShim.OSMSETS?.caphill;
if (!caphill) throw new Error('OSMSETS.caphill not found in docs/design/mapdata.js');

// ---- convert to OMT-schema GeoJSON per layer --------------------------------

type Feature = GeoJSON.Feature;
const lineCoords = (w: MockWay) => w.g.map(([lat, lon]) => [lon, lat]);
const ringCoords = (w: MockWay) => {
  const pts = lineCoords(w);
  const [fx, fy] = pts[0];
  const [lx, ly] = pts[pts.length - 1];
  if (fx !== lx || fy !== ly) pts.push([fx, fy]); // close the ring
  return [pts];
};

const OMT_CLASS: Record<number, string> = {
  4: 'motorway',
  3: 'primary',
  2: 'secondary',
  1: 'minor',
  0: 'service',
};

const layers: Record<string, Feature[]> = {
  transportation: [],
  waterway: [],
  water: [],
  park: [],
  place: [],
};

for (const way of caphill.ways) {
  if (way.g.length < 2) continue;
  if (way.k === 's') {
    layers.transportation.push({
      type: 'Feature',
      properties: { class: OMT_CLASS[way.c ?? 0], ...(way.nm ? { name: way.nm } : {}) },
      geometry: { type: 'LineString', coordinates: lineCoords(way) },
    });
  } else if (way.k === 'r') {
    layers.waterway.push({
      type: 'Feature',
      properties: { class: 'river' },
      geometry: { type: 'LineString', coordinates: lineCoords(way) },
    });
  } else if (way.k === 'w') {
    layers.water.push({
      type: 'Feature',
      properties: { class: 'lake' },
      geometry: { type: 'Polygon', coordinates: ringCoords(way) },
    });
  } else if (way.k === 'p') {
    layers.park.push({
      type: 'Feature',
      properties: { class: 'public_park', ...(way.nm ? { name: way.nm } : {}) },
      geometry: { type: 'Polygon', coordinates: ringCoords(way) },
    });
  }
}

const [S, W, N, E] = caphill.bbox;
layers.place.push(
  {
    type: 'Feature',
    properties: { name: 'Capitol Hill', class: 'suburb', rank: 10 },
    geometry: { type: 'Point', coordinates: [(W + E) / 2, (S + N) / 2] },
  },
  {
    type: 'Feature',
    properties: { name: 'Seattle', class: 'city', rank: 1 },
    geometry: { type: 'Point', coordinates: [W + 0.1 * (E - W), N - 0.3 * (N - S)] },
  }
);

// ---- cut tiles z12–14 over the bbox and encode as MVT ----------------------

const indexes = Object.fromEntries(
  Object.entries(layers).map(([name, features]) => [
    name,
    geojsonvt(
      { type: 'FeatureCollection', features },
      { maxZoom: 14, indexMaxZoom: 14, indexMaxPoints: 0, tolerance: 1.5 }
    ),
  ])
);

const nw = latLonToWorld({ lat: N, lon: W });
const se = latLonToWorld({ lat: S, lon: E });
const bboxWorld = { minX: nw[0], minY: nw[1], maxX: se[0], maxY: se[1] };

const tiles: Record<string, string> = {};
for (let z = 12; z <= 14; z++) {
  for (const t of tilesCovering(bboxWorld, z)) {
    const layerTiles: Record<string, import('geojson-vt').GeojsonVtTile> = {};
    for (const [name, index] of Object.entries(indexes)) {
      const tile = index.getTile(t.z, t.x, t.y);
      if (tile && tile.features.length) layerTiles[name] = tile;
    }
    if (!Object.keys(layerTiles).length) continue;
    const pbf: Uint8Array = vtpbf.fromGeojsonVt(layerTiles, { version: 2 });
    tiles[tileKeyOf(t.z, t.x, t.y)] = Buffer.from(pbf).toString('base64');
  }
}

// Home ≈ the mock's META.caphill.home [0.52, 0.585] fractions of the bbox.
const home = latLonToWorld({ lat: N - 0.585 * (N - S), lon: W + 0.52 * (E - W) });

const out = `/**
 * GENERATED by scripts/make-tile-fixtures.ts — do not edit.
 * Real Capitol Hill OSM geometry (docs/design/mapdata.js) cut into
 * OpenMapTiles-schema MVT tiles (z12–14), base64-encoded.
 */

import type { WorldRect } from '../../core/types';

export const FIXTURE_BOUNDS: WorldRect = ${JSON.stringify(bboxWorld)};

/** The demo "home" point (YOU / exploration seed), world coords. */
export const FIXTURE_HOME: readonly [number, number] = [${home[0]}, ${home[1]}];

export const FIXTURE_TILES: Record<string, string> = {
${Object.entries(tiles)
  .map(([k, v]) => `  '${k}': '${v}',`)
  .join('\n')}
};
`;

const outDir = join(root, 'src/features/map/tiles/__fixtures__');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'caphill-tiles.ts'), out);

const total = Object.values(tiles).reduce((n, b64) => n + b64.length, 0);
console.log(
  `wrote ${Object.keys(tiles).length} tiles (${(total / 1024).toFixed(0)} KiB base64) → src/features/map/tiles/__fixtures__/caphill-tiles.ts`
);
